"""redo

Revision ID: c1ae693488f1
Revises: 
Create Date: 2021-02-20 16:04:15.702520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ae693488f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=18), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('stock', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_manufacturer'), 'product', ['manufacturer'], unique=False)
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('stock', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manufacturer')
    op.drop_index(op.f('ix_product_manufacturer'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
